### ISSUE TITLE
Issue with SecurityEnforcer.php in Nucleus 3.70

### ISSUE THREAD

**Issue by mayank29gupta** [NucleusCMS/NucleusCMS#2]
Hi Yama,

Sorry if this is not the right platform to point out issues but lately I am having trouble in logging in to my blog. I am getting the following error - 
Warning: htmlspecialchars() [function.htmlspecialchars]: charset `_CHARSET' not supported, assuming iso-8859-1 in /home/careeing/public_html/easydestination.net/blog/nucleus/plugins/NP_SecurityEnforcer.php on line 154

Could you please take a look?

**Comment by yama** [comment]
I am very sorry for being so late.
OK, I will repair it later.
