### ISSUE TITLE
Fatal error call to undefined method in MEMBER.php

### ISSUE THREAD

**Issue by sajxe** [NucleusCMS/NucleusCMS#3]
Hi Yama, thank you for all your work on rescuing Nucleus! Just wanted to let you know that there is a problem when trying to add new team members in v. 3.70.

I was able to add two test members. When I tried to add a third member, the following error message was displayed:

Fatal error: Call to undefined method ADMIN::setPassword() in /var/www/html/user/nucleus/libs/MEMBER.php on line 682

When I replaced Member.php with the version from Leo's v3.66, it worked perfectly without errors and I was able to add more test members again. (There is a discussion about this on SlightlySome forum here: http://nucleus.slightlysome.net/forum/viewtopic.php?id=18)

Line 682 is:
else $this->setPassword($password);

Maybe it's another PHP5.x issue?

**Comment by yama** [comment]
OK, I repair it soon.

**Comment by yama** [comment]
https://github.com/NucleusCMS/NucleusCMS/blob/93b02e7f8929abf8205e40d75a832c8c8b0f22f7/nucleus/libs/MEMBER.php#L682
This issue is already fixed.

**Comment by sajxe** [comment]
Wow that was fast! Thank you very much yama!

**Comment by sajxe** [comment]
Sorry - how or where do I get the fixed version? I just re-downloaded the zip from github and replaced the member.php but it still gives me the same error as before. Not sure if I am doing something wrong...

**Comment by yama** [comment]
https://github.com/NucleusCMS/NucleusCMS/archive/master.zip
Download this archive.
Excute upgrades script, nucleus/upgrades/

**Comment by sajxe** [comment]
Just tried again according to your instructions above and still got the same error for line 682. I must be doing something wrong. I think I will wipe the database and try a clean re-install and see what happens. I may have messed up the upgrade part somehow. Sorry for the trouble and thank you for all your help!

**Comment by yama** [comment]
I am very sorry for being so late.

> Fatal error: Call to undefined method ADMIN::setPassword() in /home/careeing/public_html/easydestination.net/blog/nucleus/libs/MEMBER.php on line 682
Is it this error?
Can you have you send the files included in the nucleus/libs/ directory to me by email?
yamamoto@kyms.jp

**Comment by sajxe** [comment]
No problem, thanks very much for your help! Yes, that is the error.

I have sent you a zip of the libs folder with 3 different versions of MEMBER.php that I tested.

1) LMNucleus v3.65/3.66
No problem with adding members.

2) Japanese version 3.71 downloaded from github (master.zip)
When adding members, the following error message is shown:

Fatal error: Call to undefined method ADMIN::setPassword() in /var/www/html/user/nucleus/libs/MEMBER.php on line 572

3) Japanese version 3.70 previously downloaded from github website front page
When adding a member, the following error message is shown:

Fatal error: Call to undefined method ADMIN::setPassword() in /var/www/html/user/nucleus/libs/MEMBER.php on line 682

The email I sent you has a little bit more info but this is pretty much it.
I guess the difference between 3.70 and 3.71 line numbers is probably just because of changes that were made in the code between the two versions.

Thanks again for your help!

**Comment by piyoyo** [comment]
This problem is probably being fixed.

**Comment by yama** [comment]
Thanks.
