### ISSUE TITLE
missing close bracket in globalfunctions.php

### ISSUE THREAD

**Issue by sajxe** [NucleusCMS/NucleusCMS#4]
Hi, I just noticed that there might be a final close angle bracket missing from globalfunctions.php, right at the end of the file. 

Not sure whether it's supposed to be there in your version or not, but I checked older versions of the file, and the latest LMSS version, and they all have the usual "?>" closing tag at the end of the file.

Anyway, easy fix if it is supposed to be there, just two characters to add at the end :) I have done it on my own local copy but do not know how to use github and am not sure if I am correct, so I haven't tried to add it here. Just wanted to let you know, thanks!

[Forgot to add - I am on v3.70 but I just checked your latest version marked 3.71 on this repository and it is also still missing the closing php tag.]

**Comment by yama** [comment]
http://framework.zend.com/manual/1.12/en/coding-standard.php-file-formatting.html
Thanks. I think, closing tag is unnecessary.

**Comment by sajxe** [comment]
Ok, thanks very much yama! Please accept my apologies for the unnecessary ticket in that case!
