### ISSUE TITLE
XSS vulnerability in add an item

### ISSUE THREAD

**Issue by seshagiriprabhu** [NucleusCMS/NucleusCMS#5]
A post content with <script>alert(1);</script> would give a popup dialog box. This could be used for stealing the user cookies and thus could lead to a  session hijack. I tried it in v3.66. 
Kindly fix this issue.

**Comment by yama** [comment]
OK, Please give me more concrete information..

**Comment by seshagiriprabhu** [comment]
When I write a <script> tag within the body of the *add item,* it will get
executed as such. Usually CMSes doesn't executes <script> tags even if it
is present within the post content due to XSS issues. The below given
images are quite enough to reproduce the same.

(*Figure 1*: *While adding an item, insert script tag with alert("sample
text")*)


(*Figure 2*: *While opening up the blog post, a pop up window appears due
to the presence of alert()​ function in the item body*)


*How to fix it:* I am not an expert in PHP. There are a number of ways
hackers put to use for XSS attacks, PHP's built-in functions do not respond
to all sorts of XSS attacks. Hence, functions such as strip_tags, filter_var,
mysql_real_escape_string, htmlentities, htmlspecialchars, etc do not
protect us 100%. You need a better mechanism (a custom filtering mechanism).

As a temporary fix you could use filter_var(), The advantage of filter_var()
is that you can control the behaviour by, for example, stripping or
encoding low and high characters.


On Mon, Jul 13, 2015 at 12:22 AM, yamamoto <notifications@github.com> wrote:

> OK, Please give me more concrete information..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NucleusCMS/NucleusCMS/issues/5#issuecomment-120753975>
> .
>



-- 
Seshagiri Prabhu N
Final year computer security student,
Amrita University <http://amrita.edu/>, Amritapuri Campus, India
Blog <http://www.seshagiriprabhu.wordpress.com/> | Linkedin
<https://www.linkedin.com/pub/seshagiri-prabhu/1b/172/8ab> | Github
<https://github.com/seshagiriprabhu> | PGP
<https://pgp.mit.edu/pks/lookup?op=get&search=0x1305C413130B8BEC>

**Comment by piyoyo** [comment]
It seems better to use the wiki system than cms.

For titles, body more, it is a specification that html tags and scripts can be used. It is not a defect.

As an exception, comment items are escaped

Please do not issue user ID to unreliable person.

Nucleus CMS is multi-user system to share among trustworthy people such as family members and acquaintances.

If you do not want to allow tags, there are the following easy ways
Edit templates and skins and change to escape processing

It may use a dedicated plug-in to handle html escapes before items are displayed. (Post and Pre events)

**Comment by yama** [comment]
I see, I could understand the this problem now. This is not a vulnerability.
However, adding an option not allowing html tags may be better idea.
