### ISSUE TITLE
NP_BlogIE error 500 with PHP 7.0

### ISSUE THREAD

**Issue by sajxe** [NucleusCMS/NucleusCMS#55]
Hi, NP_BlogIE seems to fail when the server uses PHP 7.0.

I have tried this with Nucleus 3.70, 3.71, and 3.80RC and I think so far it seems to usually work if PHP is set to 5.6 or below, but if I change PHP versions to 7.0 it stops working.

The plugin can be installed, but if you click on the plugin admin link or try to use it, the browser displays  this error:

This page isn’t working
(domain) is currently unable to handle this request.
HTTP ERROR 500

If I switch back to PHP 5.6 it starts to work again.

[NP_BlogIE-0.71b.zip](https://github.com/NucleusCMS/NucleusCMS/files/1794158/NP_BlogIE-0.71b.zip)

I have attached a copy of the last version of BlogIE I could find - this is the version I am currently using. (The English Plugin Wiki link for this plugin does not work anymore)

Thanks very much for any help you can give!

**Comment by yama** [comment]
https://github.com/NucleusCMS/NP_BlogIE/archive/master.zip
Maybe fixed.

**Comment by sajxe** [comment]
Looks like it's working! Now the plugin page shows up in PHP 7 and I can export the blog contents. I didn't check the export file contents but I'm just going to assume it works :) Thank you very much! :)
