### ISSUE TITLE
System Overview display is incomplete on PHP 7.0

### ISSUE THREAD

**Issue by sajxe** [NucleusCMS/NucleusCMS#56]
I am seeing this if I switch to PHP 7.0. On PHP 5.6 it displays normally with no problems.
On php 7 the system info page will only display partly - the rest of the page will be blank.

I can see the headers on the top right of the page and a few rows of the system info table. The sidebar menu on the left does not appear and the rest of the table is cut off. The rest of the page that does not display is just blank white.

Current test Nucleus version is 3.70. (But I think I tried it with 3.71, 3.80RC and 3.80RCdev and it was the same in all cases whenever I switched to PHP 7)

My cPanel says I have:
Apache Version | 2.4.29
PHP Version | 5.6.33
MySQL Version | 5.6.39-cll-lve

But I changed it to PHP 7 in cPanel "select PHP version" and I can see the first line of the system info table in Nucleus and it says "PHP version 7.0.28" so I think it is on 7.

Not sure how much of the problem is because my webhosting company may not be very good! :) But I did try this on a few servers and the server info always cuts off if you change to PHP 7.

**Comment by yama** [comment]
https://github.com/NucleusCMS/NucleusCMS/archive/v3.8dev.zip
Can you try this? Probably, it is already fixed.

**Comment by piyopiyobird** [comment]
I think that it stopped because the 'QuickMenu' event of a plugin incompatible with PHP 7 was called.

The MANAGER::notify function is not protected with try{} catch(Error $e), so it can not continue if a fatal error occurs.

**Comment by sajxe** [comment]
I am testing both the new Technorati Tags plugin and the new 3.8dev version at the same time so I will just put one reply here, but I guess this will also apply to https://github.com/NucleusCMS/NucleusCMS/issues/57

[PS: most problems seemed to be fixed by the end of my testing, so you can probably ignore the earlier error logs if you like, and only look at the last/most recent error log I attached in #5 below. I'm just including the earlier logs in case they are of any use for troubleshooting other php/version/plugin issues]

1) I downloaded and installed the new Technorati Tags plugin. This was on php 5.6, nucleus 3.70.
Then I clicked on the TTags admin panel and the tag cloud and tag results links to test.
Here is the php error log output:
[error_log-php5-6_nuc370_newTechnoratiTags.txt](https://github.com/NucleusCMS/NucleusCMS/files/1798360/error_log-php5-6_nuc370_newTechnoratiTags.txt)

2) Then I changed to php 7.0, still on nucleus 3.70, and tested TTags links again.
Here is the php error log output:
[error_log-php7_nuc370_newTechnoratiTags.txt](https://github.com/NucleusCMS/NucleusCMS/files/1798362/error_log-php7_nuc370_newTechnoratiTags.txt)

3) Then I downloaded the new nucleus v3.8dev and upgraded.
Log output:
[error_log-php7_nuc38dev_newTechnoratiTags.txt](https://github.com/NucleusCMS/NucleusCMS/files/1798365/error_log-php7_nuc38dev_newTechnoratiTags.txt)

4) Then I started clicking around the admin control panel to test things, and I clicked on Update Subscription List in the plugins panel a few times. 
In the admin panel everything seems to be looking good now. 
As far as I can tell, System Information is loading properly and fully, and all the admin pages for the plugins are loading properly, though I have not tried to change any admin settings for any of the plugins yet.
Log outputs:
- log from the nucleus subfolder:
[error_log-nucdir-20180308b-php7_nuc380dev_newTechnoratiTags.txt](https://github.com/NucleusCMS/NucleusCMS/files/1798390/error_log-nucdir-20180308b-php7_nuc380dev_newTechnoratiTags.txt)
- log from the root subfolder one level above nucleus subfolder:
[error_log-maindir-20180308e-php7_nuc380dev_newTechnoratiTags.txt](https://github.com/NucleusCMS/NucleusCMS/files/1798393/error_log-maindir-20180308e-php7_nuc380dev_newTechnoratiTags.txt)

5) I continued to test and click around. I still have not changed any plugin settings or edited any posts.
It seems like most of the earlier problems are now fixed at this point, as I don't see the old errors in the latest log output. But now I have a new problem - the blog itself is not displaying! :)
Everything in the admin side seems to be working and displaying properly, but if I go to the blog, there is a blank white page with the words "Skin error".
 I realized I had forgotten to delete the upgrades folder, so I deleted it, but this did not fix the problem - I still get the same "Skin error" with no blog display.
The php error log seems to indicate that it is a problem with NP Access Control.
Log:
[error_log-maindir-20180308f-php7_nuc380dev_newTechnoratiTags.txt](https://github.com/NucleusCMS/NucleusCMS/files/1798403/error_log-maindir-20180308f-php7_nuc380dev_newTechnoratiTags.txt)

I think I am using the latest version of NP Access Control that I downloaded from this github repository, but I will download it again and reinstall to see if it makes any difference, and update here again after that.
In the meantime, here is a copy of the version that is currently installed on the blog:
[NPAccessControl_20180309_php7_nuc38dev.zip](https://github.com/NucleusCMS/NucleusCMS/files/1798419/NPAccessControl_20180309_php7_nuc38dev.zip)

Sorry for the long post. Thank you very much for all your help! :)

**Comment by sajxe** [comment]
Ok, downloaded, uninstalled, and reinstalled NP Access Control.
These are the log outputs - one for the nucleus subfolder and one for the main folder one level above it:
- [error_log-nucdir-20180309c-php7_nuc380dev_newTechnoratiTags.txt](https://github.com/NucleusCMS/NucleusCMS/files/1798471/error_log-nucdir-20180309c-php7_nuc380dev_newTechnoratiTags.txt)
- [error_log-maindir-20180309g-php7_nuc380dev_newTechnoratiTags.txt](https://github.com/NucleusCMS/NucleusCMS/files/1798473/error_log-maindir-20180309g-php7_nuc380dev_newTechnoratiTags.txt)
So it looks like the problem for the No Blog Display issue is with NP Access Control, NP Multiple Categories, and NP Comment Control.
I think I am using the latest versions of NP Multicats and Comment Control from this repository too but I will download and reinstall again just in case.

**Comment by sajxe** [comment]
Ok, downloaded, uninstalled and reinstalled NP Multiple Categories and NP Comment Control latest versions from this repo.
No change - admin control panel still seems to be working well now, but there is no blog display, just a white page with "Skin error".
- Error log from the NP Multiple Categories subfolder in nucleus/plugins:
[error_log-NP_MultipleCategories_latestgithub_php7-nuc380dev.txt](https://github.com/NucleusCMS/NucleusCMS/files/1798506/error_log-NP_MultipleCategories_latestgithub_php7-nuc380dev.txt)
- Error log from the NP Comment Control subfolder in nucleus/plugins:
[error_log-NP_CommentControl_latestgithub_php7-nuc380dev.txt](https://github.com/NucleusCMS/NucleusCMS/files/1798508/error_log-NP_CommentControl_latestgithub_php7-nuc380dev.txt)

Thanks very much for any help you can give!

**Comment by sajxe** [comment]
I just discovered that all of my skins in the control panel are now blank and empty after the upgrade to 3.80 dev. Maybe that's why there is a skin error :)

But when I check in phpmyadmin all the skin fields are still there. All the skin content is still there. They did not get deleted. So I guess something strange happened when I upgraded.

But when I upgraded, the message said that the databases did NOT need to be upgraded. (Successful upgrade with no errors and nothing needed to be changed)

Maybe something which should have been upgraded in the database did not get upgraded?

**Comment by sajxe** [comment]
piyopiyobird's suggestion to edit my database version in mysql and try the upgrade again worked very well. The skins are back and most things are working properly.
After testing two different versions of Nucleus, I have the following results:

**3.70 + php7**
NP blogie works
NP technorati tags works - the plugin admin page may not display properly using latest version - only part of the page displays. If you move the plugin up the plugin list it may display properly again.
NP access control works properly
NP random does not work (quotes do not display - I think the errors are mostly the same as what you see in the logs I've attached above)
System info does not work (table is cut off after one and a half lines and the rest of the page does not display)

**3.80 dev + php7**
NP Blogie works
NP technorati tags  works
System info works
NP Access control does not work properly (Only get individual "this item is protected" instead of full blog lock, and can still see menu, categories, post timestamps, etc.)
NP random does not work (quotes do not display)

**Comment by piyopiyobird** [comment]
Nucleus v3.70 is not supported php7.

Nucleus    | supported php version
------------ | -------------
v3.70 release | PHP5

github   | supported php version
------------ | -------------
v3.8dev(v3.80) | PHP5, PHP7.0, PHP7.1, PHP7.2

**Comment by sajxe** [comment]
Thanks very much piyopiyobird! Unfortunately I am testing this on two subdomains in the same domain so the PHP version I set in cPanel is shared with both :) But happily that means I can call this issue fixed since it is only because of php 7 :)

I will open a separate thread for the NP Random / NP Access Control issues and close this one, since it was only supposed to be about System Overview. Thanks very much once again!

**Comment by yama** [comment]
https://github.com/NucleusCMS/NP_AccessControl
Maybe fixed
