### ISSUE TITLE
Error when changing admin area style

### ISSUE THREAD

**Issue by sajxe** [NucleusCMS/NucleusCMS#59]
System info: PHP 7, mysql 5.6.39, nucleus 3.80 dev

Steps to reproduce:

1) Go to Management > Configuration> Admin Area Style
2) Change from any style to any other style and click Update Settings.

Result:

Blank white page with the following error message:
Query error: Duplicate entry 'ENABLE_TIDY_FORCE_HT' for key 'PRIMARY'

- I have left the three new settings on default (disabled):
[disabled] Enable html auto-formatting by Tidy
[disabled] Tidy: Force HTML5
[disabled] Tidy: Indent the html tag

I have not tried changing any other settings in the Configuration panel yet but I'm guessing any change submitted there could result in this error message.

This does not seem to be a serious error. When I reload the Configuration page, my admin area style change shows as having taken effect and everything is still loading and displaying normally on that page.

**Comment by piyopiyobird** [comment]
your v3.80dev database seems to be old.
Please downgrade the database number once and start the upgrade script.

setep1
`UPDATE nucleus_config SET value='371' WHERE name='DatabaseVersion';`
step2
Go to the upgrade page.
_upgrades/


-------------------------------------
-v3.71
CREATE TABLE `nucleus_config` (
  `name`  varchar(**20**)  NOT NULL default '',

v3.80
CREATE TABLE `nucleus_config` (
  `name`  varchar(**50**)  NOT NULL default '',

(23) ENABLE_TIDY_FORCE_HTML5
(20) **ENABLE_TIDY_FORCE_HT**

**Comment by sajxe** [comment]
Thank you very much! I tried this and everything in the control panel seemed to be working and displaying properly. But the plugins seem to be having a lot of problems now. Technorati Tags, NP Random, and Access Control are all acting strangely now, so the blog is not displaying properly when protected or when I try to test the tags.

I also noticed that in phpmyadmin, these three tables can no longer be manually edited:
nucleus_plugin
nucleus_plugin_option
nucleus_plugin_option_desc

In my old working installations these three tables have edit links that you can click and manually edit in phpmyadmin. Now there is a message in phpmyadmin that says:
" Current selection does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available."
Is it supposed to be like that after upgrade?
If not, something may have been messed up and I will have to try again.

Maybe I have just tried too many different upgrades and I should try to do a clean install and just import the blog entries and skins separately after that :)

**Comment by sajxe** [comment]
I will close this issue because the TIDY error seems to be fixed with a proper database upgrade, and update more about the other plugin issues in the other issue thread. Thank you very much piyopiyobird!
