### ISSUE TITLE
Cannot post to Nucleus forum?

### ISSUE THREAD

**Issue by sajxe** [NucleusCMS/NucleusCMS#6]
Hi Yama,

I'm very excited to see that the Japanese team has brought back the old Nucleus website. Thank you for continuing to work on Nucleus! Your blog post says we can post to the old English forum, but I cannot find a way to do so. Is posting still disabled on the old forum? Sorry to post this here but I did not know how else to contact the board admins. Thanks very much!

**Comment by osamuh** [comment]
I have just posted a test message at http://www.nucleuscms.org/forum/viewtopic.php?f=15&t=21357 and it seems working fine for me.
Could you kindly please clarify the issue a little more?
More info like the URL you tried to post, error message you got, etc. would be greatly helpful.

Thanks.

**Comment by sajxe** [comment]
Sorry, should have provided more info! Maybe it's just that I am not looking in the right place. After I log in, I cannot seem to find any button that allows me to add a new post or even reply to a post. I'm still looking now and all I see is options for searching, subscribing, etc. But not for posting or replying.

**Comment by sajxe** [comment]
Forgot to say - is the board still set to only allow Admins to post or something like that, maybe?

**Comment by osamuh** [comment]
It looks like that the forum permission settings were not correct, and I have reset them now.
Could you please give it a try again?

Thanks!

**Comment by sajxe** [comment]
Yes! I can see the New Topic and Post Reply buttons now. Looks like it's fixed! Thank you very much Osamuh!
