### ISSUE TITLE
NP Access Control and NP Random in v3.80dev with PHP 7.0

### ISSUE THREAD

**Issue by sajxe** [NucleusCMS/NucleusCMS#60]
**NP Random:** [fixed! :) 2018-03-14]
Random quote file does not display. 
The file is correctly formatted and is uploaded in the correct path/folder - it was working before in a previous version but is not working now.
I tried changing to php 5.6 but it still did not display. I will keep testing.

**NP Access Control:**
Plugin options are displaying correctly in control panel.
It is set for Only to Logged in Users, loginform skin, No basic auth access to RSS, Use skin restriction.
I tried adding the special tags skins and the loginform skin to the Allowed Skins field but it did not make any difference.
Normally the whole blog should be protected and there would be a page with just a log in form.
Instead I can see the whole blog except for the post titles and post bodies.
Blog layout (background image and design), categories, sidebar menu and post timestamps are all visible.

This has happened before and sometimes it seemed to get fixed after I changed something, but it's always different so I'm not sure what the problem really is.
Right now this is working normally for me in v3.70 and only the 3.80dev copy is having this problem. 

Thanks for any suggestions you can give!

**Comment by sajxe** [comment]
Here are two clean log files from a simple test of NP Access Control. I logged out, tried to load the blog index page a few times, then logged in and loaded the blog again.

- Log from Nucleus subfolder:
[error_log-test-nucdir-380devphp7-accesscontrolissues-2018-03-09a.txt](https://github.com/NucleusCMS/NucleusCMS/files/1799137/error_log-test-nucdir-380devphp7-accesscontrolissues-2018-03-09a.txt)
- Log from main folder one level above:
[error_log-test-maindir-380devphp7-accesscontrolissues-2018-03-09a.txt](https://github.com/NucleusCMS/NucleusCMS/files/1799139/error_log-test-maindir-380devphp7-accesscontrolissues-2018-03-09a.txt)

**Comment by yama** [comment]
https://github.com/NucleusCMS/NP_AccessControl
https://github.com/NucleusCMS/NP_Random
Maybe fixed

**Comment by sajxe** [comment]
Thank you very much! I uninstalled the old plugins and re-installed the new ones. There was no change - still no random quote display and still no full-blog protection.

I thought of trying an older version since that works sometimes. So I uninstalled the plugins again and installed NP Access Control v.1.42 instead. It worked!!! :) I don't know why but it is now working perfectly. (Nucleus v3.80dev + php7 + mysql 5.39).

Here is a copy of the version that worked, in case anyone needs it:
[NP_AccessControl-master_2016-02-12_v1.42.zip](https://github.com/NucleusCMS/NucleusCMS/files/1801011/NP_AccessControl-master_2016-02-12_v1.42.zip)

I also tried installing v1.1 of NP Random but that did not work :( But at least this issue is half fixed now :)
I will keep testing :)

**Comment by yama** [comment]
ok, I'll fix them later.

**Comment by sajxe** [comment]
Ok! I gave up on NP Random for now, but the good news is I found another random quotes plugin that does work with 3.80dev and php 7 :)

This is a very old plugin but surprisingly it works perfectly. I'm not sure whether the developer's website still exists but I had saved the original example quote file and instructions so here is a copy for anyone who needs it :)

[NP_RandomQuote_v1.1.zip](https://github.com/NucleusCMS/NucleusCMS/files/1801039/NP_RandomQuote_v1.1.zip)

It does roughly the same thing as NP Random, the only (minor) difference is a time delay setting. I will use this in the meantime until NP Random is fixed.

Thank you very much for all your help! :)

**Comment by yama** [comment]
https://github.com/NucleusCMS/NP_Random
Maybe fixed

**Comment by sajxe** [comment]
The new version of NP Random works! I've tried it on three blogs, one with an upgraded slightly older version of 3.80dev, one with a clean new 3.80dev just downloaded yesterday, and one with my old 3.70, all are using php7. It works on all of them now. Thank you so much! :)

I am still testing the new NP Access Control but so far it still seems the same, no change on older upgraded 3.80dev + php7. I can install/upgrade the plugin, but it protects only the post titles and bodies but not the whole blog.

On a clean new install of 3.80dev (latest version downloaded yesterday), the plugin does not install properly.
- If I upload it and update the plugin subscription list, I get an error 500 page.
- Then when I try to go back and reload the admin panel plugin page, it stops displaying after the first table row. The control panel side menu does not display and the rest of the page does not display.
- I have to delete the new version and reload the page to get it to display properly again.

I may try to upgrade my old 3.70 to 3.71 stable soon. I'll try this new plugin again then as well. Thanks very much for all your help with this!

**Comment by sajxe** [comment]
My blogs and plugins all mostly seem to be working well now, so I will close this ticket. Thanks very much!
