### ISSUE TITLE
403 Forbidden error when trying to edit template

### ISSUE THREAD

**Issue by sajxe** [NucleusCMS/NucleusCMS#61]
I tried this with v3.70 and v3.80dev, on both php 5.6 and php 7.0. The result is the same.
When I try to edit a template and click on "Update template", I get the following error message:

> Forbidden
> You don't have permission to access /nucleus/index.php on this server.
> Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

This does not happen with skin files. I can edit skins in the control panel with no problems.
I can also work around this by editing the template in phpmyadmin, so it is not a serious issue.

Do I need to set any special permissions for the file or folder? 
This webhost sets all folders to 755 and all files to 644 by default.

I don't have this problem on another server with Nucleus v.3.80, PHP 7.0.27 and MySQL : 5.7.21, so I'm wondering whether it is a problem with the web host.

I noticed that if this happens a few times, my web host will auto-block my IP address. So maybe something that happens when I try to edit a template looks like a hack attempt to the web host?? (This happens even if I don't make any changes to the existing template - I only need to click on "Update template" and the error message will be displayed.)

I am not sure where to check to find out what the problem is. The server log does not show any errors.
Thanks for any suggestions you can give!

**Comment by yama** [comment]
https://www.google.com/search?q=waf
Maybe WAF? (Web Application Firewall)

**Comment by sajxe** [comment]
Thanks very much for the tip, you were right!
It turned out that my webhost had enabled ModSecurity by default on the account.
Luckily it could be manually disabled in cPanel.
When I disabled it and tested again, I was finally able to edit a template in both 3.70 and 3.80dev!
Thanks very much once again for all your help! :)
