### ISSUE TITLE
nucleuscms.org website down

### ISSUE THREAD

**Issue by sajxe** [NucleusCMS/NucleusCMS#7]
Just to let you guys know the website seems to be down. If you go to nucleuscms.org, the error message is:

Error 503 Service Unavailable
Service Unavailable
Guru Meditation:
XID: 1901752842
Varnish cache server

If you go to http://nucleuscms.org/forum/ the error message is:

Error 503 Service Unavailable
Service Unavailable
Guru Meditation:
XID: 735174545
Varnish cache server

**Comment by yama** [comment]
Thanks. I decide to use alive monitoring service.

**Comment by sajxe** [comment]
Good idea! :) Thanks very much yama!

**Comment by sajxe** [comment]
Oops, I closed it too soon. The forum seems to be down now!
If you try to log in to the forum, you get the following error message:
	
General Error
Illegal use of $_REQUEST. You must use the request class or request_var() to access input data. Found in /home/project-web/nucleuscms/htdocs/forum/ucp.php on line 35. This error message was generated by deactivated_super_global.

Please notify the board administrator or webmaster: [email address removed to avoid spam] @lists.sourceforge.net

If you already know about this issue then please feel free to close this thread.

Thanks very much!

**Comment by yama** [comment]
Thanks, I repaired it.
